init:
  - git config --global core.autocrlf input

os:
 - Visual Studio 2015
 - Visual Studio 2017

platform:
  - Win32

configuration:
  - Debug
  - Release

before_build:
  - git submodule update --init --recursive
  - mkdir build
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - cd build
  - cmake ..

build:
  project: C:/projects/caches/build/caches.sln

test_script:
  - cmd: ctest -C %CONFIGURATION% -V 
