init:
  - git config --global core.autocrlf input

os:
 - Visual Studio 2015
 - Visual Studio 2017
 - Visual Studio 2019

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - git submodule update --init --recursive
  - echo %arch%
  - mkdir build
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( SET GEN="Visual Studio 14 2015" )
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( SET GEN="Visual Studio 15 2017" )
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2019" ( SET GEN="Visual Studio 16 2019" )
  - cd build
  - IF NOT "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2019" (
      cmake .. -G %GEN%
    ) ELSE (
      cmake .. -G %GEN% -A %PLATFORM%
    )

build:
  project: C:/projects/caches/build/caches.sln

test_script:
  - cmd: ctest -C %CONFIGURATION% -V 
