init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - image: Visual Studio 2015
    - image: Visual Studio 2017

platform:
  - Win32

configuration:
  - Debug
  - Release

before_build:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ..

build:
  project: C:/projects/caches/build/caches.sln

test_script:
  - cmd: ctest -C %CONFIGURATION% -V 
