name: Documentation
on:
  release:
    types:
      - published

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: "Install doxygen"
        run: |
          wget -qO- https://www.doxygen.nl/files/doxygen-1.9.2.linux.bin.tar.gz | tar zxf -
          echo "$(readlink -f doxygen-1.9.2/bin)" >> $GITHUB_PATH
      - name: "Configure project"
        run: |
          mkdir build
          cmake -B build -S .
          cmake --build build
      - name: "Run tests"
        run: ctest
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Setup pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: "Build documentation"
        run: |
          cmake --build build --target docs
          pushd docs/mkdocs
          pipenv install --deploy
          pipenv run mkdocs build
          popd
      - name: "Publish documentation"
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
        run:
          ./docupages.py -t ${GITHUB_TOKEN} -r "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" --commit ${GITHUB_SHA} -b gh-pages
