name: Documentation
on:
  release:
    types:
      - published

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: "Install doxygen"
        run: |
          wget -qO- https://github.com/doxygen/doxygen/releases/download/Release_1_9_6/doxygen-1.9.6.linux.bin.tar.gz | tar zxf -
          echo "$(readlink -f doxygen-1.9.6/bin)" >> $GITHUB_PATH
          sudo apt install graphviz
      - name: "Configure project"
        run: |
          mkdir build
          cmake -B build -S .
          cmake --build build
      - name: "Run tests"
        run: ctest
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: 'Setup poetry'
        run: python -m pip install --upgrade poetry wheel
      - name: "Build documentation"
        run: |
          cmake --build build --target docs
          pushd docs/mkdocs
          poetry install
          poetry run mkdocs build
          popd
      - name: "Publish documentation"
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
        run:
          ./docupages.py -t ${GITHUB_TOKEN} -r "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" --commit ${GITHUB_SHA} -b gh-pages
